version: '3.8'
services: 
  db:
    container_name: pgpro_course
    image: postgres:16.0
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      # - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
  pg_admin:
    container_name: pgpro_course_admin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
volumes:
  data:
    driver: local